### ISSUE TITLE
Add caching to travis file 

### ISSUE THREAD

**Issue by sarahjean** [Drupal4Gov/Drupal-GovCon-2017#28]
Here's an example of travis caching for vendor/node_modules from the cog theme:
```
env:
  global:
    - DOCROOT=$TRAVIS_BUILD_DIR/../drupal
    - COG_DIR=$DOCROOT/themes/contrib/cog
    - COGNIZANT_DIR=$DOCROOT/themes/custom/cognizant

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.composer/vendor"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "$COGNIZANT_DIR/node_modules"
```
